### PR TITLE
actions: Create build workflow

### PR DESCRIPTION
**Pull request by raffenet**
Initial implementation of GitHub Actions workflow. Add scripts to
install autotools and MPI libraries. Build OSHMPI with MPICH. The plan
is to extend this to build and test with other MPI configurations.

### CODE REVIEW

**Comment by raffenet** [comment]
Yes, we can rename it. Any suggestion?

**Comment by raffenet** [comment]
Here is a suggestion: this configuration can be `CI: build-mpich`. As we extend the configurations we can have `CI: build-openmpi`, `CI:test-mpich-shm`, etc.

**Comment by minsii** [comment]
The names look great to me!

**Comment by raffenet** [comment]
Updated names and added build-openmpi configuration. This should take effect once merged.

**Comment by minsii** [comment]
Looks like the change of automake version causes failure in jenkins job: https://jenkins-pmrs.cels.anl.gov/view/oshmpi/job/oshmpi-review-sostest-mpich-ch4-ofi/compiler=intel,oshmpi_configs=default,queue=centos64_review/60/artifact/autogen.txt

Why did we update it to 1.15.1?

**Comment by minsii** [comment]
Emm, I see why we updated it. The action job needs it. Let me see if I can fix the autogen script

**Comment by raffenet** [comment]
Hmm, I forget exactly why I had updated it. I vaguely remember having issues with 1.15 install in the actions environment. It should be fine to revert for now. I can fix it up tomorrow.

**Comment by raffenet** [comment]
It looks like this is why I wanted to bump it.

http://gnu-automake.7480.n7.nabble.com/bug-29178-Failure-to-build-automake-gt-11-td22684.html

There is a conflict with pre-1.15.1 versions of automake and the system perl on Ubuntu 18.04, which is what Actions uses.

**Comment by raffenet** [comment]
> It looks like this is why I wanted to bump it.
> 
> http://gnu-automake.7480.n7.nabble.com/bug-29178-Failure-to-build-automake-gt-11-td22684.html
> 
> There is a conflict with pre-1.15.1 versions of automake and the system perl on Ubuntu 18.04, which is what Actions uses.

One thing I can do is modify the GitHub Actions workflow to use a Docker image that has all the autotools pre-installed. I actually defined one for MPICH was back that uses the exact versions originally in `autogen.sh`. Let me see if I can get it working in my fork.

**Comment by minsii** [comment]
I copied the autotools version check code from mpich/autogen.sh. See here: https://github.com/pmodels/oshmpi/pull/66

It works on Action machine now.

**Comment by minsii** [comment]
I just pushed the autogen change to master branch by mistake :-(

**Comment by raffenet** [comment]
No worries. That's a more robust solution in any case. I can still do the Docker image update, just need to bump the version.

**Pull request merged**
