### PR TITLE
shmemx: define gpu symm heap alloc|free

### PR DESCRIPTION
**Pull request by minsii**

### CODE REVIEW

**Comment by jeffhammond** [comment]
Perhaps `s/GPU/CUDA/g` to allow for non-CUDA GPU programming models to be integrated later?

**Comment by minsii** [comment]
@jeffhammond Makes sense. This is just a very initial prototype. The committee is also considering a hint based API to deal with HEAP on device memory (see https://github.com/openshmem-org/specification/issues/258).

I am considering two possible interfaces in OSHMPI:
- We expose `shmemx_X_malloc` API to deal with device buffer allocation with the X programming model (e.g., `X` can be cuda, openCL,...). In such case, should we expect that only one model is used at runtime ? Otherwise, we have to initialize multiple device heaps at init time. Actually user can configure OSHMPI to support all models, and disable|enable the X-heap by environment variable.
- The user program allocates the device buffer, and registers the buffer pointer to shmem as symm heap. This is more flexible and similar to `MPI_win_create`. Will we allow user to register arbitrary number of heaps similar to MPI window ? This may cause heavy win lookup overhead in RMA operation.

**Comment by jeffhammond** [comment]
I would not expect more than one GPU etc model to be used at a time. I’d rather have that limitation than have an expensive address lookup.

I though OpenSHMEM was going to add features for multiple heaps. Did that not happen?

**Comment by minsii** [comment]
No multiple heaps in current spec yet. I think it is being addressed in the partition proposal.

Sent from my iPhone

On Aug 21, 2019, at 8:58 PM, Jeff Hammond <notifications@github.com<mailto:notifications@github.com>> wrote:

I would not expect more than one GPU etc model to be used at a time. I’d rather have that limitation than have an expensive address lookup.

I though OpenSHMEM was going to add features for multiple heaps. Did that not happen?

**Comment by minsii** [comment]
Close the PR as we are currently implementing the memory space proposal being discussed for OpenSHMEM 1.6. The initial implementation has already merged via #68

**Pull request closed without merging**
