### PR TITLE
ZE support

### PR DESCRIPTION
**Pull request by raffenet**
Initial support for Level Zero device memory support. TODO: add test case.

Refs #103.

### CODE REVIEW

**Comment by raffenet** [comment]
This should contain everything need to create spaces with ZE memkind. I have not yet written code to test reading/writing to those memory regions. I prefer to leave that to April, if it can wait until then.

**Comment by raffenet** [comment]
Oh, I need to fix non-ZE builds. Force push coming shortly...

**Comment by minsii** [comment]
@raffenet Thanks. The PR looks good to me assuming that manual test has been done. To add a basic write/read test for ze, can we simply reuse the `space_int_put|amo` test?  I'd prefer to have at least checked basic functionalities.

**Comment by minsii** [comment]
test:oshmpi/mpich/builtin
test:oshmpi/ompi/builtin

**Comment by minsii** [comment]
test:oshmpi/mpich/builtin
test:oshmpi/ompi/builtin

**Comment by raffenet** [comment]
> @raffenet Thanks. The PR looks good to me assuming that manual test has been done. To add a basic write/read test for ze, can we simply reuse the `space_int_put|amo` test? I'd prefer to have at least checked basic functionalities.

I can give it a shot. With ZE, unlike `cudaMemcpy`, we need to create a stream and enqueue the operations onto it then wait for them to complete. I can probably copy/paste what is in the MPICH test suite with a little bit of work.

**Comment by raffenet** [comment]
> I can give it a shot. With ZE, unlike `cudaMemcpy`, we need to create a stream and enqueue the operations onto it then wait for them to complete. I can probably copy/paste what is in the MPICH test suite with a little bit of work.

Basically there is a bunch of initialization and setup work that needs to go into `gpu_common.h` or otherwise. Might take another day or 2.

**Comment by minsii** [comment]
The plan sounds good to me. Thanks! I will approve this PR and merge it, as it is for space creation. The RMA/AMO tests and potential fixes can be in with a separate PR.

**Review by minsii — APPROVED** [review]

**Pull request merged**
